# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db5d47da4aff236e147c03f51e2bfa4253e808ad0d8c822eba6db49a972756f524c5fe9e5cc53db693c30ce38fa9c4053ad9441a91fdf9a6a0c51ae38e67b9b2

test:
  secret_key_base: b1f548686b33e67716ef5cd7bddc94626a4bc78d6832a053a8f2732dc2d428607432ced67e346a50a1ef33757c395d91addd2650203c3124f5cc72455435d944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
